//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainTcpServer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name sName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.InsertResponse Insert(BlockChainTcpServer.ServiceReference1.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.InsertResponse> InsertAsync(BlockChainTcpServer.ServiceReference1.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name sName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.CreateUserResponse CreateUser(BlockChainTcpServer.ServiceReference1.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.CreateUserResponse> CreateUserAsync(BlockChainTcpServer.ServiceReference1.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name sHash from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToBlockChain", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse AddToBlockChain(BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToBlockChain", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse> AddToBlockChainAsync(BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest request);
        
        // CODEGEN: Generating message contract since element name sHash from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.ValidateResponse Validate(BlockChainTcpServer.ServiceReference1.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.ValidateResponse> ValidateAsync(BlockChainTcpServer.ServiceReference1.ValidateRequest request);
        
        // CODEGEN: Generating message contract since element name sHash from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoOfDocument", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse GetInfoOfDocument(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoOfDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse> GetInfoOfDocumentAsync(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetBlockChainResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlockChain", ReplyAction="*")]
        BlockChainTcpServer.ServiceReference1.GetBlockChainResponse GetBlockChain(BlockChainTcpServer.ServiceReference1.GetBlockChainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlockChain", ReplyAction="*")]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetBlockChainResponse> GetBlockChainAsync(BlockChainTcpServer.ServiceReference1.GetBlockChainRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(BlockChainTcpServer.ServiceReference1.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sCreationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] bData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int iUserID;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(string sName, string sType, string sCreationDate, string sHash, byte[] bData, int iUserID) {
            this.sName = sName;
            this.sType = sType;
            this.sCreationDate = sCreationDate;
            this.sHash = sHash;
            this.bData = bData;
            this.iUserID = iUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(BlockChainTcpServer.ServiceReference1.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(string InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(BlockChainTcpServer.ServiceReference1.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sEmail;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string sName, string sPassword, string sEmail) {
            this.sName = sName;
            this.sPassword = sPassword;
            this.sEmail = sEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(BlockChainTcpServer.ServiceReference1.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(string CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToBlockChainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToBlockChain", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.AddToBlockChainRequestBody Body;
        
        public AddToBlockChainRequest() {
        }
        
        public AddToBlockChainRequest(BlockChainTcpServer.ServiceReference1.AddToBlockChainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToBlockChainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserID;
        
        public AddToBlockChainRequestBody() {
        }
        
        public AddToBlockChainRequestBody(string sHash, string sUserID) {
            this.sHash = sHash;
            this.sUserID = sUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToBlockChainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToBlockChainResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.AddToBlockChainResponseBody Body;
        
        public AddToBlockChainResponse() {
        }
        
        public AddToBlockChainResponse(BlockChainTcpServer.ServiceReference1.AddToBlockChainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToBlockChainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddToBlockChainResult;
        
        public AddToBlockChainResponseBody() {
        }
        
        public AddToBlockChainResponseBody(bool AddToBlockChainResult) {
            this.AddToBlockChainResult = AddToBlockChainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(BlockChainTcpServer.ServiceReference1.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sHash;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string sHash) {
            this.sHash = sHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(BlockChainTcpServer.ServiceReference1.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(bool ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoOfDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoOfDocument", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequestBody Body;
        
        public GetInfoOfDocumentRequest() {
        }
        
        public GetInfoOfDocumentRequest(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoOfDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sHash;
        
        public GetInfoOfDocumentRequestBody() {
        }
        
        public GetInfoOfDocumentRequestBody(string sHash) {
            this.sHash = sHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoOfDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoOfDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponseBody Body;
        
        public GetInfoOfDocumentResponse() {
        }
        
        public GetInfoOfDocumentResponse(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoOfDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetInfoOfDocumentResult;
        
        public GetInfoOfDocumentResponseBody() {
        }
        
        public GetInfoOfDocumentResponseBody(byte[] GetInfoOfDocumentResult) {
            this.GetInfoOfDocumentResult = GetInfoOfDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlockChainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlockChain", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.GetBlockChainRequestBody Body;
        
        public GetBlockChainRequest() {
        }
        
        public GetBlockChainRequest(BlockChainTcpServer.ServiceReference1.GetBlockChainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBlockChainRequestBody {
        
        public GetBlockChainRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlockChainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlockChainResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlockChainTcpServer.ServiceReference1.GetBlockChainResponseBody Body;
        
        public GetBlockChainResponse() {
        }
        
        public GetBlockChainResponse(BlockChainTcpServer.ServiceReference1.GetBlockChainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBlockChainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetBlockChainResult;
        
        public GetBlockChainResponseBody() {
        }
        
        public GetBlockChainResponseBody(byte[] GetBlockChainResult) {
            this.GetBlockChainResult = GetBlockChainResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BlockChainTcpServer.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BlockChainTcpServer.ServiceReference1.ServiceSoap>, BlockChainTcpServer.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.InsertResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.Insert(BlockChainTcpServer.ServiceReference1.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public string Insert(string sName, string sType, string sCreationDate, string sHash, byte[] bData, int iUserID) {
            BlockChainTcpServer.ServiceReference1.InsertRequest inValue = new BlockChainTcpServer.ServiceReference1.InsertRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.InsertRequestBody();
            inValue.Body.sName = sName;
            inValue.Body.sType = sType;
            inValue.Body.sCreationDate = sCreationDate;
            inValue.Body.sHash = sHash;
            inValue.Body.bData = bData;
            inValue.Body.iUserID = iUserID;
            BlockChainTcpServer.ServiceReference1.InsertResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.InsertResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.InsertAsync(BlockChainTcpServer.ServiceReference1.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.InsertResponse> InsertAsync(string sName, string sType, string sCreationDate, string sHash, byte[] bData, int iUserID) {
            BlockChainTcpServer.ServiceReference1.InsertRequest inValue = new BlockChainTcpServer.ServiceReference1.InsertRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.InsertRequestBody();
            inValue.Body.sName = sName;
            inValue.Body.sType = sType;
            inValue.Body.sCreationDate = sCreationDate;
            inValue.Body.sHash = sHash;
            inValue.Body.bData = bData;
            inValue.Body.iUserID = iUserID;
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.CreateUserResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.CreateUser(BlockChainTcpServer.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public string CreateUser(string sName, string sPassword, string sEmail) {
            BlockChainTcpServer.ServiceReference1.CreateUserRequest inValue = new BlockChainTcpServer.ServiceReference1.CreateUserRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.CreateUserRequestBody();
            inValue.Body.sName = sName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sEmail = sEmail;
            BlockChainTcpServer.ServiceReference1.CreateUserResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.CreateUserResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.CreateUserAsync(BlockChainTcpServer.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.CreateUserResponse> CreateUserAsync(string sName, string sPassword, string sEmail) {
            BlockChainTcpServer.ServiceReference1.CreateUserRequest inValue = new BlockChainTcpServer.ServiceReference1.CreateUserRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.CreateUserRequestBody();
            inValue.Body.sName = sName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sEmail = sEmail;
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.AddToBlockChain(BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest request) {
            return base.Channel.AddToBlockChain(request);
        }
        
        public bool AddToBlockChain(string sHash, string sUserID) {
            BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest inValue = new BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.AddToBlockChainRequestBody();
            inValue.Body.sHash = sHash;
            inValue.Body.sUserID = sUserID;
            BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).AddToBlockChain(inValue);
            return retVal.Body.AddToBlockChainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.AddToBlockChainAsync(BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest request) {
            return base.Channel.AddToBlockChainAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.AddToBlockChainResponse> AddToBlockChainAsync(string sHash, string sUserID) {
            BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest inValue = new BlockChainTcpServer.ServiceReference1.AddToBlockChainRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.AddToBlockChainRequestBody();
            inValue.Body.sHash = sHash;
            inValue.Body.sUserID = sUserID;
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).AddToBlockChainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.ValidateResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.Validate(BlockChainTcpServer.ServiceReference1.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public bool Validate(string sHash) {
            BlockChainTcpServer.ServiceReference1.ValidateRequest inValue = new BlockChainTcpServer.ServiceReference1.ValidateRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.ValidateRequestBody();
            inValue.Body.sHash = sHash;
            BlockChainTcpServer.ServiceReference1.ValidateResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.ValidateResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.ValidateAsync(BlockChainTcpServer.ServiceReference1.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.ValidateResponse> ValidateAsync(string sHash) {
            BlockChainTcpServer.ServiceReference1.ValidateRequest inValue = new BlockChainTcpServer.ServiceReference1.ValidateRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.ValidateRequestBody();
            inValue.Body.sHash = sHash;
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).ValidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.GetInfoOfDocument(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest request) {
            return base.Channel.GetInfoOfDocument(request);
        }
        
        public byte[] GetInfoOfDocument(string sHash) {
            BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest inValue = new BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequestBody();
            inValue.Body.sHash = sHash;
            BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).GetInfoOfDocument(inValue);
            return retVal.Body.GetInfoOfDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.GetInfoOfDocumentAsync(BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest request) {
            return base.Channel.GetInfoOfDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentResponse> GetInfoOfDocumentAsync(string sHash) {
            BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest inValue = new BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.GetInfoOfDocumentRequestBody();
            inValue.Body.sHash = sHash;
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).GetInfoOfDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlockChainTcpServer.ServiceReference1.GetBlockChainResponse BlockChainTcpServer.ServiceReference1.ServiceSoap.GetBlockChain(BlockChainTcpServer.ServiceReference1.GetBlockChainRequest request) {
            return base.Channel.GetBlockChain(request);
        }
        
        public byte[] GetBlockChain() {
            BlockChainTcpServer.ServiceReference1.GetBlockChainRequest inValue = new BlockChainTcpServer.ServiceReference1.GetBlockChainRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.GetBlockChainRequestBody();
            BlockChainTcpServer.ServiceReference1.GetBlockChainResponse retVal = ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).GetBlockChain(inValue);
            return retVal.Body.GetBlockChainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetBlockChainResponse> BlockChainTcpServer.ServiceReference1.ServiceSoap.GetBlockChainAsync(BlockChainTcpServer.ServiceReference1.GetBlockChainRequest request) {
            return base.Channel.GetBlockChainAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlockChainTcpServer.ServiceReference1.GetBlockChainResponse> GetBlockChainAsync() {
            BlockChainTcpServer.ServiceReference1.GetBlockChainRequest inValue = new BlockChainTcpServer.ServiceReference1.GetBlockChainRequest();
            inValue.Body = new BlockChainTcpServer.ServiceReference1.GetBlockChainRequestBody();
            return ((BlockChainTcpServer.ServiceReference1.ServiceSoap)(this)).GetBlockChainAsync(inValue);
        }
    }
}
